server:
  port: 8899
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_1?useUnicode=true&characterEncoding=utf8
        username: root
        password: qpm123
    application:
      name: consume-service

mybatis:
  type-aliases-package: com.raincat.dubbo.sample.consume.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.raincat.bonuspoint: info
        com.raincat.lottery: info
        com.raincat: info
        io.netty: info

    path: "./logs"


